spring:
  application:
    name: democjava-client

server:
  port: 8072
 
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
            defaultZone: http://10.2.219.74:8761/eureka/
  instance:
    hostname: localhost     
    


